// Send Request from Localhost
### 
GET http://localhost:8080/contacts 
### 
GET http://localhost:8080/contacts/62a90cd1086347c641f9eef8 
### 
GET http://localhost:8080/contacts/62a90cd1086347c641f9eef9 
### 
GET http://localhost:8080/contacts/62a90cd1086347c641f9eefa

// Send request from Heroku
### 
GET https://cse341-jermain-clients.herokuapp.com/contacts/
### 
GET https://cse341-jermain-clients.herokuapp.com/contacts/62a90cd1086347c641f9eef8
### 
GET https://cse341-jermain-clients.herokuapp.com/contacts/62a90cd1086347c641f9eef9 
### 
GET https://cse341-jermain-clients.herokuapp.com/contacts/62a90cd1086347c641f9eefa
