// Send Request from Localhost
### 
GET http://localhost:8080/contacts/ 

### create a contact POST
POST http://localhost:8080/contacts/ HTTP/1.1
Content-Type: application/json

{   
    "firstName":"Renzo",
    "lastName":"Funez",
    "email": "renzo@gmail.com",
    "favoriteColor":"Yellow",
    "birthday":"11/10/97"
}

### PUT contact by Id
PUT http://localhost:8080/contacts/62aaaa3a086347c641f9eeff HTTP/1.1
Content-Type: application/json

{
    "firstName": "Alexi",
    "lastName": "Lopez",
    "email": "alexislopez@outlook.com",
    "favoriteColor": "Red",
    "birthday": "01/09/98"
}
### DELETE contact by Id
DELETE http://localhost:8080/contacts/62a90cd1086347c641f9eefa

### 
GET http://localhost:8080/contacts/62aaaa3a086347c641f9eefe
### 
GET http://localhost:8080/contacts/62aaaa3a086347c641f9eeff
### 
GET http://localhost:8080/contacts/62aaaa3a086347c641f9ef00

// Send request from Heroku
### 
GET https://cse341-jermain-clients.herokuapp.com/contacts/
### create a contact POST
POST https://cse341-jermain-clients.herokuapp.com/contacts HTTP/1.1
Content-Type: application/json

{   
    "firstName": "Renzo",
    "lastName": "Funez",
    "email": "renzo@gmail.com",
    "favoriteColor": "Yellow",
    "birthday": "11/10/97"
}
### PUT contact by Id
PUT https://cse341-jermain-clients.herokuapp.com/contacts/62aaaa3a086347c641f9ef00 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Kenneth",
    "lastName": "Flores",
    "email": "kennethdaniel@gmail.com",
    "favoriteColor": "Green",
    "birthday": "10/11/99"
}
### DELETE contact by Id
DELETE https://cse341-jermain-clients.herokuapp.com/contacts/62aaae3ebea053490f814957
### 
GET https://cse341-jermain-clients.herokuapp.com/contacts/62aaaa3a086347c641f9eefe
### 
GET https://cse341-jermain-clients.herokuapp.com/contacts/62aaaa3a086347c641f9eeff 
### 
GET https://cse341-jermain-clients.herokuapp.com/contacts/62aaaa3a086347c641f9ef00

